# Generated by Django 4.1.7 on 2023-04-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(blank=True, max_length=17, null=True)),
                ('Productname', models.CharField(blank=True, max_length=23, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('Descriptions', models.CharField(blank=True, max_length=1000, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
