# Generated by Django 4.1.7 on 2023-04-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0002_productdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='Image',
            new_name='Images',
        ),
    ]
