# Generated by Django 4.1.7 on 2023-04-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=34, null=True)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Password', models.CharField(blank=True, max_length=40, null=True)),
                ('Cpassword', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
