# Generated by Django 4.1.7 on 2023-05-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(blank=True, max_length=34, null=True)),
                ('Pprice', models.IntegerField(blank=True, null=True)),
                ('PQ', models.IntegerField(blank=True, null=True)),
                ('Ptotal_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
