# Generated by Django 4.1.7 on 2023-05-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='User',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
